#!/bin/bash

code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcasella.monokai-plusplus
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension idleberg.applescript
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension mikestead.dotenv
code --install-extension mkloubert.vscode-remote-workspace
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension oderwat.indent-rainbow
code --install-extension p1c2u.docker-compose
code --install-extension patbenatar.advanced-new-file
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension robertohuertasm.vscode-icons
code --install-extension rogalmic.bash-debug
code --install-extension rpinski.shebang-snippets
code --install-extension shanoor.vscode-nginx
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension slevesque.vscode-autohotkey
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tickleforce.scrolloff
code --install-extension timonwong.shellcheck
code --install-extension truman.autocomplate-shell
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhouronghui.propertylist
